time_zone: "Hanoi"
email:
  time_expired: 2
role:
  admin: "admin"
  trainee: "trainee"
course:
  status:
    active: "Activated"
    not_active: "Not activated"
    progress: "In progress"
    finish: "Finish"
